"""Initial schema generation

Revision ID: 1bded21b4a94
Revises: 
Create Date: 2026-02-04 22:10:22.107451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bded21b4a94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accessorials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('is_percentage', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('air_cost_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=5), nullable=False),
    sa.Column('min_charge', sa.Float(), nullable=False),
    sa.Column('per_lb', sa.Float(), nullable=False),
    sa.Column('weight_break', sa.Float(), nullable=False),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_set', 'zone', name='uq_air_cost_zones_rate_set_zone')
    )
    op.create_index(op.f('ix_air_cost_zones_rate_set'), 'air_cost_zones', ['rate_set'], unique=False)
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('beyond_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=5), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('up_to_miles', sa.Float(), nullable=False),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beyond_rates_rate_set'), 'beyond_rates', ['rate_set'], unique=False)
    op.create_table('cost_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concat', sa.String(length=5), nullable=False),
    sa.Column('cost_zone', sa.String(length=5), nullable=False),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_set', 'concat', name='uq_cost_zones_rate_set_concat')
    )
    op.create_index(op.f('ix_cost_zones_rate_set'), 'cost_zones', ['rate_set'], unique=False)
    op.create_table('hotshot_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('miles', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=5), nullable=False),
    sa.Column('per_lb', sa.Float(), nullable=False),
    sa.Column('per_mile', sa.Float(), nullable=True),
    sa.Column('min_charge', sa.Float(), nullable=False),
    sa.Column('weight_break', sa.Float(), nullable=True),
    sa.Column('fuel_pct', sa.Float(), nullable=False),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotshot_rates_rate_set'), 'hotshot_rates', ['rate_set'], unique=False)
    op.create_table('rate_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=120), nullable=True),
    sa.Column('company_phone', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('customer', 'employee', 'super_admin', name='user_role'), nullable=False),
    sa.Column('employee_approved', sa.Boolean(), nullable=False),
    sa.Column('admin_previous_role', sa.Enum('customer', 'employee', name='user_admin_previous_role'), nullable=True),
    sa.Column('admin_previous_employee_approved', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_rate_set'), 'users', ['rate_set'], unique=False)
    op.create_table('zip_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zipcode', sa.String(length=10), nullable=False),
    sa.Column('dest_zone', sa.Integer(), nullable=False),
    sa.Column('beyond', sa.String(length=20), nullable=True),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_set', 'zipcode', name='uq_zip_zones_rate_set_zipcode')
    )
    op.create_index(op.f('ix_zip_zones_rate_set'), 'zip_zones', ['rate_set'], unique=False)
    op.create_table('email_dispatch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('quote_type', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(length=20), nullable=True),
    sa.Column('destination', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('weight_method', sa.String(length=20), nullable=True),
    sa.Column('actual_weight', sa.Float(), nullable=True),
    sa.Column('dim_weight', sa.Float(), nullable=True),
    sa.Column('pieces', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('zone', sa.String(length=5), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('quote_metadata', sa.Text(), nullable=True),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.Column('request_ip', sa.String(length=45), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id')
    )
    op.create_index(op.f('ix_quotes_rate_set'), 'quotes', ['rate_set'], unique=False)
    op.create_index(op.f('ix_quotes_request_ip'), 'quotes', ['request_ip'], unique=False)
    op.create_table('email_quote_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('shipper_name', sa.String(), nullable=True),
    sa.Column('shipper_address', sa.String(), nullable=True),
    sa.Column('shipper_contact', sa.String(), nullable=True),
    sa.Column('shipper_phone', sa.String(), nullable=True),
    sa.Column('consignee_name', sa.String(), nullable=True),
    sa.Column('consignee_address', sa.String(), nullable=True),
    sa.Column('consignee_contact', sa.String(), nullable=True),
    sa.Column('consignee_phone', sa.String(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('special_instructions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.quote_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_quote_requests')
    op.drop_index(op.f('ix_quotes_request_ip'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_rate_set'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_table('password_reset_tokens')
    op.drop_table('email_dispatch_log')
    op.drop_index(op.f('ix_zip_zones_rate_set'), table_name='zip_zones')
    op.drop_table('zip_zones')
    op.drop_index(op.f('ix_users_rate_set'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('rate_uploads')
    op.drop_index(op.f('ix_hotshot_rates_rate_set'), table_name='hotshot_rates')
    op.drop_table('hotshot_rates')
    op.drop_index(op.f('ix_cost_zones_rate_set'), table_name='cost_zones')
    op.drop_table('cost_zones')
    op.drop_index(op.f('ix_beyond_rates_rate_set'), table_name='beyond_rates')
    op.drop_table('beyond_rates')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_air_cost_zones_rate_set'), table_name='air_cost_zones')
    op.drop_table('air_cost_zones')
    op.drop_table('accessorials')
    # ### end Alembic commands ###
