"""add can_send_mail to user

Revision ID: 84eccfd5f119
Revises: 1bded21b4a94
Create Date: 2026-02-06 17:43:14.587270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84eccfd5f119"
down_revision: Union[str, Sequence[str], None] = "1bded21b4a94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "can_send_mail",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.alter_column("users", "can_send_mail", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "can_send_mail")
    # ### end Alembic commands ###
