"""restore_schema

Revision ID: e4f54f4a0a95
Revises: 
Create Date: 2026-01-27 18:12:28.064445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f54f4a0a95'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_logo_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_set', sa.String(length=50), nullable=False),
    sa.Column('gcs_bucket_location', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_logo_locations_rate_set'), 'brand_logo_locations', ['rate_set'], unique=True)
    op.drop_index(op.f('ix_email_dispatch_log_feature'), table_name='email_dispatch_log')
    op.drop_index(op.f('ix_email_dispatch_log_recipient'), table_name='email_dispatch_log')
    op.drop_index(op.f('ix_email_dispatch_log_user_id'), table_name='email_dispatch_log')
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('quotes', 'quote_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('quotes', 'quote_metadata',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('quotes', 'ip_address')
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('quotes', sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.alter_column('quotes', 'quote_metadata',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('quotes', 'quote_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('password_reset_tokens', 'used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('password_reset_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_email_dispatch_log_user_id'), 'email_dispatch_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_email_dispatch_log_recipient'), 'email_dispatch_log', ['recipient'], unique=False)
    op.create_index(op.f('ix_email_dispatch_log_feature'), 'email_dispatch_log', ['feature'], unique=False)
    op.drop_index(op.f('ix_brand_logo_locations_rate_set'), table_name='brand_logo_locations')
    op.drop_table('brand_logo_locations')
    # ### end Alembic commands ###
